name: ci

on:
  pull_request:
    branches:
      - master

jobs:

  test:
    name: Run npm test in supported nodejs versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x]
    steps:
    - name: Checkout project code
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test